apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
  selector:
    matchLabels:
      app: commandservice    
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: aces32/commandservice:latest
  replicas: 1
