apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  selector:
    matchLabels:
      app: platformservice    
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: aces32/platformservice:latest
  replicas: 1
